services:
  app:
    build: .
    container_name: vroom
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - CONFIG_PATH=/application/config/local.yaml
    volumes:
      - ./config:/application/config:ro
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=vroom
      - POSTGRES_PASSWORD=vroom
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: