services:
  app:
    build: .
    container_name: vroom
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - CONFIG_PATH=/application/config/local.yaml
    volumes:
      - ./config:/application/config:ro
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgis/postgis:16-3.4
    environment:
      - POSTGRES_PASSWORD=vroom
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  goose:
    build: ./tools/goose
    container_name: goose
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
    entrypoint: ["/goose/entrypoint.sh"]
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: vroom
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: