// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: reservation/v1/reservation.proto

package reservation_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReservationStatus int32

const (
	ReservationStatus_RESERVATION_STATUS_UNSPECIFIED ReservationStatus = 0
	ReservationStatus_RESERVATION_STATUS_ACTIVE      ReservationStatus = 1
	ReservationStatus_RESERVATION_STATUS_COMPLETED   ReservationStatus = 2
	ReservationStatus_RESERVATION_STATUS_CANCELLED   ReservationStatus = 3
)

// Enum value maps for ReservationStatus.
var (
	ReservationStatus_name = map[int32]string{
		0: "RESERVATION_STATUS_UNSPECIFIED",
		1: "RESERVATION_STATUS_ACTIVE",
		2: "RESERVATION_STATUS_COMPLETED",
		3: "RESERVATION_STATUS_CANCELLED",
	}
	ReservationStatus_value = map[string]int32{
		"RESERVATION_STATUS_UNSPECIFIED": 0,
		"RESERVATION_STATUS_ACTIVE":      1,
		"RESERVATION_STATUS_COMPLETED":   2,
		"RESERVATION_STATUS_CANCELLED":   3,
	}
)

func (x ReservationStatus) Enum() *ReservationStatus {
	p := new(ReservationStatus)
	*p = x
	return p
}

func (x ReservationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReservationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_reservation_v1_reservation_proto_enumTypes[0].Descriptor()
}

func (ReservationStatus) Type() protoreflect.EnumType {
	return &file_reservation_v1_reservation_proto_enumTypes[0]
}

func (x ReservationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReservationStatus.Descriptor instead.
func (ReservationStatus) EnumDescriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{0}
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Point) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type Reservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    int64                  `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CarId         int64                  `protobuf:"varint,3,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	StartLocation *Point                 `protobuf:"bytes,6,opt,name=start_location,json=startLocation,proto3" json:"start_location,omitempty"`
	EndLocation   *Point                 `protobuf:"bytes,7,opt,name=end_location,json=endLocation,proto3" json:"end_location,omitempty"`
	TotalPrice    string                 `protobuf:"bytes,8,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Status        ReservationStatus      `protobuf:"varint,9,opt,name=status,proto3,enum=reservation.v1.ReservationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{1}
}

func (x *Reservation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Reservation) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *Reservation) GetCarId() int64 {
	if x != nil {
		return x.CarId
	}
	return 0
}

func (x *Reservation) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *Reservation) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *Reservation) GetStartLocation() *Point {
	if x != nil {
		return x.StartLocation
	}
	return nil
}

func (x *Reservation) GetEndLocation() *Point {
	if x != nil {
		return x.EndLocation
	}
	return nil
}

func (x *Reservation) GetTotalPrice() string {
	if x != nil {
		return x.TotalPrice
	}
	return ""
}

func (x *Reservation) GetStatus() ReservationStatus {
	if x != nil {
		return x.Status
	}
	return ReservationStatus_RESERVATION_STATUS_UNSPECIFIED
}

type CreateReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarId         int64                  `protobuf:"varint,1,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	StartLocation *Point                 `protobuf:"bytes,4,opt,name=start_location,json=startLocation,proto3" json:"start_location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationRequest) Reset() {
	*x = CreateReservationRequest{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationRequest) ProtoMessage() {}

func (x *CreateReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationRequest.ProtoReflect.Descriptor instead.
func (*CreateReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{2}
}

func (x *CreateReservationRequest) GetCarId() int64 {
	if x != nil {
		return x.CarId
	}
	return 0
}

func (x *CreateReservationRequest) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *CreateReservationRequest) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *CreateReservationRequest) GetStartLocation() *Point {
	if x != nil {
		return x.StartLocation
	}
	return nil
}

type CreateReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId int64                  `protobuf:"varint,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationResponse) Reset() {
	*x = CreateReservationResponse{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationResponse) ProtoMessage() {}

func (x *CreateReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationResponse.ProtoReflect.Descriptor instead.
func (*CreateReservationResponse) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{3}
}

func (x *CreateReservationResponse) GetReservationId() int64 {
	if x != nil {
		return x.ReservationId
	}
	return 0
}

type ListReservationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReservationsRequest) Reset() {
	*x = ListReservationsRequest{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReservationsRequest) ProtoMessage() {}

func (x *ListReservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReservationsRequest.ProtoReflect.Descriptor instead.
func (*ListReservationsRequest) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{4}
}

type ListReservationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservations  []*Reservation         `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReservationsResponse) Reset() {
	*x = ListReservationsResponse{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReservationsResponse) ProtoMessage() {}

func (x *ListReservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReservationsResponse.ProtoReflect.Descriptor instead.
func (*ListReservationsResponse) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{5}
}

func (x *ListReservationsResponse) GetReservations() []*Reservation {
	if x != nil {
		return x.Reservations
	}
	return nil
}

type GetReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationRequest) Reset() {
	*x = GetReservationRequest{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationRequest) ProtoMessage() {}

func (x *GetReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationRequest.ProtoReflect.Descriptor instead.
func (*GetReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{6}
}

func (x *GetReservationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   *Reservation           `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationResponse) Reset() {
	*x = GetReservationResponse{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationResponse) ProtoMessage() {}

func (x *GetReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationResponse.ProtoReflect.Descriptor instead.
func (*GetReservationResponse) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{7}
}

func (x *GetReservationResponse) GetReservation() *Reservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

type CompleteReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EndLocation   *Point                 `protobuf:"bytes,2,opt,name=end_location,json=endLocation,proto3" json:"end_location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteReservationRequest) Reset() {
	*x = CompleteReservationRequest{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteReservationRequest) ProtoMessage() {}

func (x *CompleteReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteReservationRequest.ProtoReflect.Descriptor instead.
func (*CompleteReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{8}
}

func (x *CompleteReservationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CompleteReservationRequest) GetEndLocation() *Point {
	if x != nil {
		return x.EndLocation
	}
	return nil
}

type CompleteReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteReservationResponse) Reset() {
	*x = CompleteReservationResponse{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteReservationResponse) ProtoMessage() {}

func (x *CompleteReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteReservationResponse.ProtoReflect.Descriptor instead.
func (*CompleteReservationResponse) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteReservationResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type CancelReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationRequest) Reset() {
	*x = CancelReservationRequest{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationRequest) ProtoMessage() {}

func (x *CancelReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationRequest.ProtoReflect.Descriptor instead.
func (*CancelReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{10}
}

func (x *CancelReservationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CancelReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationResponse) Reset() {
	*x = CancelReservationResponse{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationResponse) ProtoMessage() {}

func (x *CancelReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationResponse.ProtoReflect.Descriptor instead.
func (*CancelReservationResponse) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{11}
}

func (x *CancelReservationResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

var File_reservation_v1_reservation_proto protoreflect.FileDescriptor

const file_reservation_v1_reservation_proto_rawDesc = "" +
	"\n" +
	" reservation/v1/reservation.proto\x12\x0ereservation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15bin/annotations.proto\"+\n" +
	"\x05Point\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\"\x93\x03\n" +
	"\vReservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\x03R\n" +
	"customerId\x12\x15\n" +
	"\x06car_id\x18\x03 \x01(\x03R\x05carId\x125\n" +
	"\bstart_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\x12<\n" +
	"\x0estart_location\x18\x06 \x01(\v2\x15.reservation.v1.PointR\rstartLocation\x128\n" +
	"\fend_location\x18\a \x01(\v2\x15.reservation.v1.PointR\vendLocation\x12\x1f\n" +
	"\vtotal_price\x18\b \x01(\tR\n" +
	"totalPrice\x129\n" +
	"\x06status\x18\t \x01(\x0e2!.reservation.v1.ReservationStatusR\x06status\"\xd9\x01\n" +
	"\x18CreateReservationRequest\x12\x15\n" +
	"\x06car_id\x18\x01 \x01(\x03R\x05carId\x125\n" +
	"\bstart_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\x12<\n" +
	"\x0estart_location\x18\x04 \x01(\v2\x15.reservation.v1.PointR\rstartLocation\"B\n" +
	"\x19CreateReservationResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\x03R\rreservationId\"\x19\n" +
	"\x17ListReservationsRequest\"[\n" +
	"\x18ListReservationsResponse\x12?\n" +
	"\freservations\x18\x01 \x03(\v2\x1b.reservation.v1.ReservationR\freservations\"'\n" +
	"\x15GetReservationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"W\n" +
	"\x16GetReservationResponse\x12=\n" +
	"\vreservation\x18\x01 \x01(\v2\x1b.reservation.v1.ReservationR\vreservation\"f\n" +
	"\x1aCompleteReservationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x128\n" +
	"\fend_location\x18\x02 \x01(\v2\x15.reservation.v1.PointR\vendLocation\"K\n" +
	"\x1bCompleteReservationResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"*\n" +
	"\x18CancelReservationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"I\n" +
	"\x19CancelReservationResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty*\x9a\x01\n" +
	"\x11ReservationStatus\x12\"\n" +
	"\x1eRESERVATION_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19RESERVATION_STATUS_ACTIVE\x10\x01\x12 \n" +
	"\x1cRESERVATION_STATUS_COMPLETED\x10\x02\x12 \n" +
	"\x1cRESERVATION_STATUS_CANCELLED\x10\x032\xcd\x05\n" +
	"\x12ReservationService\x12\x85\x01\n" +
	"\x11CreateReservation\x12(.reservation.v1.CreateReservationRequest\x1a).reservation.v1.CreateReservationResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/reservations\x12\x7f\n" +
	"\x10ListReservations\x12'.reservation.v1.ListReservationsRequest\x1a(.reservation.v1.ListReservationsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/reservations\x12~\n" +
	"\x0eGetReservation\x12%.reservation.v1.GetReservationRequest\x1a&.reservation.v1.GetReservationResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/reservations/{id}\x12\x99\x01\n" +
	"\x13CompleteReservation\x12*.reservation.v1.CompleteReservationRequest\x1a+.reservation.v1.CompleteReservationResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/reservations/{id}/complete\x12\x91\x01\n" +
	"\x11CancelReservation\x12(.reservation.v1.CancelReservationRequest\x1a).reservation.v1.CancelReservationResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/reservations/{id}/cancelB@Z>github.com/folivorra/vroom/proto/reservation/v1;reservation_v1b\x06proto3"

var (
	file_reservation_v1_reservation_proto_rawDescOnce sync.Once
	file_reservation_v1_reservation_proto_rawDescData []byte
)

func file_reservation_v1_reservation_proto_rawDescGZIP() []byte {
	file_reservation_v1_reservation_proto_rawDescOnce.Do(func() {
		file_reservation_v1_reservation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reservation_v1_reservation_proto_rawDesc), len(file_reservation_v1_reservation_proto_rawDesc)))
	})
	return file_reservation_v1_reservation_proto_rawDescData
}

var file_reservation_v1_reservation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_reservation_v1_reservation_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_reservation_v1_reservation_proto_goTypes = []any{
	(ReservationStatus)(0),              // 0: reservation.v1.ReservationStatus
	(*Point)(nil),                       // 1: reservation.v1.Point
	(*Reservation)(nil),                 // 2: reservation.v1.Reservation
	(*CreateReservationRequest)(nil),    // 3: reservation.v1.CreateReservationRequest
	(*CreateReservationResponse)(nil),   // 4: reservation.v1.CreateReservationResponse
	(*ListReservationsRequest)(nil),     // 5: reservation.v1.ListReservationsRequest
	(*ListReservationsResponse)(nil),    // 6: reservation.v1.ListReservationsResponse
	(*GetReservationRequest)(nil),       // 7: reservation.v1.GetReservationRequest
	(*GetReservationResponse)(nil),      // 8: reservation.v1.GetReservationResponse
	(*CompleteReservationRequest)(nil),  // 9: reservation.v1.CompleteReservationRequest
	(*CompleteReservationResponse)(nil), // 10: reservation.v1.CompleteReservationResponse
	(*CancelReservationRequest)(nil),    // 11: reservation.v1.CancelReservationRequest
	(*CancelReservationResponse)(nil),   // 12: reservation.v1.CancelReservationResponse
	(*timestamppb.Timestamp)(nil),       // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 14: google.protobuf.Empty
}
var file_reservation_v1_reservation_proto_depIdxs = []int32{
	13, // 0: reservation.v1.Reservation.start_at:type_name -> google.protobuf.Timestamp
	13, // 1: reservation.v1.Reservation.end_at:type_name -> google.protobuf.Timestamp
	1,  // 2: reservation.v1.Reservation.start_location:type_name -> reservation.v1.Point
	1,  // 3: reservation.v1.Reservation.end_location:type_name -> reservation.v1.Point
	0,  // 4: reservation.v1.Reservation.status:type_name -> reservation.v1.ReservationStatus
	13, // 5: reservation.v1.CreateReservationRequest.start_at:type_name -> google.protobuf.Timestamp
	13, // 6: reservation.v1.CreateReservationRequest.end_at:type_name -> google.protobuf.Timestamp
	1,  // 7: reservation.v1.CreateReservationRequest.start_location:type_name -> reservation.v1.Point
	2,  // 8: reservation.v1.ListReservationsResponse.reservations:type_name -> reservation.v1.Reservation
	2,  // 9: reservation.v1.GetReservationResponse.reservation:type_name -> reservation.v1.Reservation
	1,  // 10: reservation.v1.CompleteReservationRequest.end_location:type_name -> reservation.v1.Point
	14, // 11: reservation.v1.CompleteReservationResponse.empty:type_name -> google.protobuf.Empty
	14, // 12: reservation.v1.CancelReservationResponse.empty:type_name -> google.protobuf.Empty
	3,  // 13: reservation.v1.ReservationService.CreateReservation:input_type -> reservation.v1.CreateReservationRequest
	5,  // 14: reservation.v1.ReservationService.ListReservations:input_type -> reservation.v1.ListReservationsRequest
	7,  // 15: reservation.v1.ReservationService.GetReservation:input_type -> reservation.v1.GetReservationRequest
	9,  // 16: reservation.v1.ReservationService.CompleteReservation:input_type -> reservation.v1.CompleteReservationRequest
	11, // 17: reservation.v1.ReservationService.CancelReservation:input_type -> reservation.v1.CancelReservationRequest
	4,  // 18: reservation.v1.ReservationService.CreateReservation:output_type -> reservation.v1.CreateReservationResponse
	6,  // 19: reservation.v1.ReservationService.ListReservations:output_type -> reservation.v1.ListReservationsResponse
	8,  // 20: reservation.v1.ReservationService.GetReservation:output_type -> reservation.v1.GetReservationResponse
	10, // 21: reservation.v1.ReservationService.CompleteReservation:output_type -> reservation.v1.CompleteReservationResponse
	12, // 22: reservation.v1.ReservationService.CancelReservation:output_type -> reservation.v1.CancelReservationResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_reservation_v1_reservation_proto_init() }
func file_reservation_v1_reservation_proto_init() {
	if File_reservation_v1_reservation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reservation_v1_reservation_proto_rawDesc), len(file_reservation_v1_reservation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reservation_v1_reservation_proto_goTypes,
		DependencyIndexes: file_reservation_v1_reservation_proto_depIdxs,
		EnumInfos:         file_reservation_v1_reservation_proto_enumTypes,
		MessageInfos:      file_reservation_v1_reservation_proto_msgTypes,
	}.Build()
	File_reservation_v1_reservation_proto = out.File
	file_reservation_v1_reservation_proto_goTypes = nil
	file_reservation_v1_reservation_proto_depIdxs = nil
}
